services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "80:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  golang:
    image: golang:1.22
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - go_cache:/root/.cache/go-build
      - go_mod:/go/pkg/mod
    command: bash -c "cd /app && go run cmd/api/main.go"
volumes:
  postgres_data:
  pgadmin_data:
  go_cache:
  go_mod:
