services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate
    command: [
      "-path", "/database/migration",
      "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable",
      "up"
    ]
    volumes:
      - ./database/migration:/database/migration
    depends_on:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "80:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  golang:
    image: golang:1.22
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      API_PORT: ${API_PORT}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${API_PORT}:8080"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - go_cache:/root/.cache/go-build
      - go_mod:/go/pkg/mod
    command: bash -c "cd /app && go run cmd/api/main.go"
volumes:
  postgres_data:
  pgadmin_data:
  go_cache:
  go_mod:
